name: 'C++ CI - Multiplatform Release'

on:
  push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
      
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-linux
          path: |
            ./helloworld-0.0.${{ github.run_number }}-Linux.deb
            ./helloworld-0.0.${{ github.run_number }}-Linux.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
      

      - name: Install Boost via Chocolatey
        run: choco install boost -y

      - name: Configure CMake
        run: |
          cmake . -DPATCH_VERSION=${{ github.run_number }}
          mkdir build
          cd build
          cmake .. -DBOOST_ROOT="C:/local/boost_1_83_0"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release
      
      - name: Run tests
        run: ctest -C Release --verbose
      
      - name: Pack
        run: cpack --config CPackConfig.cmake
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-windows
          path: |
            helloworld-${{ github.run_number }}-Windows.zip
            package/helloworld.exe
          retention-days: 5

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: helloworld-linux
          path: ./artifacts/linux
      
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: helloworld-windows
          path: ./artifacts/windows
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          body: |
            Automated release for commit ${{ github.sha }}
            
            **Changes:**
            - Auto-generated release
            - Multiplatform support (Linux + Windows)
            
            **Assets:**
            - Linux: DEB package and tar.gz
            - Windows: ZIP archive with executable
            
            Built from branch: ${{ github.ref }}
      
      - name: Upload Linux DEB Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
      
      - name: Upload Linux Tar.gz Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/helloworld-0.0.${{ github.run_number }}-Linux.tar.gz
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.tar.gz
          asset_content_type: application/gzip
      
      - name: Upload Windows ZIP Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/helloworld-${{ github.run_number }}-Windows.zip
          asset_name: helloworld-${{ github.run_number }}-Windows.zip
          asset_content_type: application/zip
      
      - name: Upload Windows EXE Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/helloworld.exe
          asset_name: helloworld-${{ github.run_number }}-Windows.exe
          asset_content_type: application/vnd.microsoft.portable-executable